#homebrewを最新版にアップデート
update || true

# Formulaを更新
upgrade || true

# Add Repository
tap homebrew/versions    || true
tap phinze/homebrew-cask || true
tap homebrew/binary      || true
tap thoughtbot/formulae  || true

# パッケージのインストール
install subversion || true

# editor
install vim   || true

## Git
install git   || true
install hub   || true
install gitsh || true
install gist  || true
install tig   || true
install gibo  || true

## Utils
install wget      || true
install curl      || true
install tree      || true
install openssl   || true
install libyaml   || true
install readline  || true
install tmux      || true
install markdown  || true
install nkf       || true
install ag        || true

## Image
install imagemagick || true

# Casks
install brew-cask
cask install google-chrome || true
cask install iterm2        || true
cask install dropbox       || true
cask install hipchat       || true
cask install alfred        || true
cask install sourcetree    || true
cask install evernote      || true
cask install kobito        || true
cask install sublime-text  || true
cask install virtualbox    || true
cask install vagrant       || true
cask install slate         || true
cask install Cyberduck     || true

# Remove outdated versions
cleanup
